# Generated by Django 3.1.3 on 2021-03-02 07:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210301_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(max_length=200, null=True)),
                ('one_month', models.CharField(max_length=200, null=True)),
                ('two_months', models.CharField(max_length=200, null=True)),
                ('three_months', models.CharField(max_length=200, null=True)),
                ('four_months', models.CharField(max_length=200, null=True)),
                ('five_months', models.CharField(max_length=200, null=True)),
                ('six_month', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 2, 7, 49, 18, 220503, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentplan', to='dashboard.paymentplan'),
        ),
    ]
