# Generated by Django 3.1.3 on 2021-03-02 08:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210302_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentplan',
            name='five_months',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='four_months',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='one_month',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='six_month',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='three_months',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='two_months',
        ),
        migrations.AddField(
            model_name='order',
            name='five_months',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='four_months',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='one_month',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='six_months',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='three_months',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='two_months',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 2, 8, 3, 4, 289884, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
