# Generated by Django 3.1.3 on 2021-03-02 08:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210302_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image_five',
            field=models.ImageField(default='assets/images/products/img01.jpg', upload_to='orders/'),
        ),
        migrations.AddField(
            model_name='order',
            name='image_four',
            field=models.ImageField(default='assets/images/products/img01.jpg', upload_to='orders/'),
        ),
        migrations.AddField(
            model_name='order',
            name='image_one',
            field=models.ImageField(default='assets/images/products/img01.jpg', upload_to='orders/'),
        ),
        migrations.AddField(
            model_name='order',
            name='image_six',
            field=models.ImageField(default='assets/images/products/img01.jpg', upload_to='orders/'),
        ),
        migrations.AddField(
            model_name='order',
            name='image_three',
            field=models.ImageField(default='assets/images/products/img01.jpg', upload_to='orders/'),
        ),
        migrations.AddField(
            model_name='order',
            name='image_two',
            field=models.ImageField(default='assets/images/products/img01.jpg', upload_to='orders/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 2, 8, 10, 42, 979423, tzinfo=utc)),
        ),
    ]
