# Generated by Django 3.1.3 on 2021-03-03 14:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20210303_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 3, 14, 40, 30, 565976, tzinfo=utc)),
        ),
    ]
