# Generated by Django 3.1.3 on 2021-07-12 18:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20210712_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 12, 18, 57, 43, 185150, tzinfo=utc)),
        ),
    ]
