# Generated by Django 3.1.3 on 2021-07-12 19:13

import cloudinary.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20210712_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 12, 19, 13, 48, 7950, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank='true', default='assets/images/products/img01.jpg', max_length=255, null='true'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_four',
            field=cloudinary.models.CloudinaryField(blank='true', default='assets/images/products/img01.jpg', max_length=255, null='true'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_one',
            field=cloudinary.models.CloudinaryField(blank='true', default='assets/images/products/img01.jpg', max_length=255, null='true'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_three',
            field=cloudinary.models.CloudinaryField(blank='true', default='assets/images/products/img01.jpg', max_length=255, null='true'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_two',
            field=cloudinary.models.CloudinaryField(blank='true', default='assets/images/products/img01.jpg', max_length=255, null='true'),
        ),
    ]
