# Generated by Django 3.1.3 on 2021-03-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerreg_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreg',
            name='order',
        ),
    ]
