# Generated by Django 3.1.3 on 2021-03-03 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210303_1311'),
        ('accounts', '0003_remove_customerreg_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreg',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='dashboard.order'),
        ),
    ]
