# Generated by Django 3.1.3 on 2021-07-12 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20210712_1957'),
        ('accounts', '0004_customerreg_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreg',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='dashboard.order'),
        ),
    ]
